language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y curl git unzip libxml2-dev

install:
   - composer install --no-interaction -o